name: rsync-with-ssh-agent
author: Martin Schmitt
description: Sync files by rsync with SSH key, agent and passphrase
branding:
  color: green
  icon: folder
inputs:
  SSH_KEY:
    description: 'SSH identity'
    required: true
  SSH_PASSPHRASE:
    description: 'Passphrase for SSH identity'
    required: true
  SSH_USER:
    description: 'SSH remote user'
    required: true
  SSH_HOST:
    description: 'SSH remote host'
    required: true
  SSH_PORT:
    description: 'SSH port on remote host (default 22)'
    required: false
    default: '22'
  RSYNC_OPTIONS:
    description: 'additional rsync options'
    required: false
    default: '--dry-run'
  RSYNC_LOCAL_PATH:
    description: 'rsync local source path'
    required: false
    default: '.'
  RSYNC_REMOTE_PATH:
    description: 'rsync remote destination path (default .)'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
  - run: install -D -m 600 /dev/null ~/.ssh/id && echo '${{ inputs.SSH_KEY }}' > ~/.ssh/id
    shell: sh
  - run: ssh-agent -a ~/.ssh/agent.socket > ~/.ssh/agent.env
    shell: sh
  - run: |
      cat > ~/.ssh/config <<-Here
      StrictHostKeyChecking accept-new
      IdentityFile ~/.ssh/id
      IdentitiesOnly yes
      User ${{ inputs.SSH_USER }}
      Host remote
      Hostname ${{ inputs.SSH_HOST }}
      Port ${{ inputs.SSH_PORT }}
      Here
    shell: sh
  - run: cat ~/.ssh/config
    shell: sh
  - run: . ~/.ssh/agent.env; echo '${{ inputs.SSH_PASSPHRASE }}' | ssh-add ~/.ssh/id
    shell: sh
  - run: . ~/.ssh/agent.env; ssh-add -l
    shell: sh
  - run: . ~/.ssh/agent.env; rsync ${{ inputs.RSYNC_OPTIONS }} --exclude '.*' --recursive --delete-excluded --verbose '${{ inputs.RSYNC_LOCAL_PATH }}' 'remote:${{ inputs.RSYNC_REMOTE_PATH }}'
    shell: sh
  - run: . ~/.ssh/agent.env; ssh-agent -k; rm ~/.ssh/id
    if: success() || failure()
    shell: sh
