name: rsync tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate test file (plain)
        run: mkdir 'plain'; openssl rand -hex 4 > 'plain/test.txt'
      - name: Generate test file (space)
        run: mkdir 'spa ce'; openssl rand -hex 4 > 'spa ce/test.txt'
      - name: Generate test file (umlaut)
        run: mkdir 'umlaüt'; openssl rand -hex 4 > 'umlaüt/test.txt'
      - name: Upload plain
        uses: mschmitt/rsync-with-ssh-agent@HEAD
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          RSYNC_REMOTE_PATH: 'plain'
          RSYNC_LOCAL_PATH: 'plain'
          RSYNC_OPTIONS: ''
      - name: Upload space
        uses: mschmitt/rsync-with-ssh-agent@HEAD
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          RSYNC_REMOTE_PATH: 'spa\ ce'
          RSYNC_LOCAL_PATH: 'spa ce'
          RSYNC_OPTIONS: ''
      - name: Upload umlaut
        uses: mschmitt/rsync-with-ssh-agent@HEAD
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          RSYNC_REMOTE_PATH: 'umlaüt'
          RSYNC_LOCAL_PATH: 'umlaüt'
          RSYNC_OPTIONS: ''
      - name: Diff back (plain)
        run: diff 'plain/test.txt' <(curl https://${{ secrets.SSH_HOST }}/testarea/plain/plain/test.txt)
      - name: Diff back (space)
        run: diff 'spa ce/test.txt' <(curl https://${{ secrets.SSH_HOST }}/testarea/spa%20ce/spa%20ce/test.txt)
      - name: Diff back (umlaut)
        run: diff 'umlaüt/test.txt' <(curl https://${{ secrets.SSH_HOST }}/testarea/umla%C3%BCt/umla%C3%BCt/test.txt)
